export const filters = {
  brightness: 0,
  contrast: 0,
  exposure: 0,
  temperature: 0,
  tint: 0,
  hue: 0,
  saturation: 0,
  value: 0,
  black: 1,
  white: 255,
  gamma: 1,
  outblack: 0,
  outwhite: 255,
  red_red_channel: 100,
  red_green_channel: 0,
  red_blue_channel: 0,
  green_red_channel: 0,
  green_green_channel: 100,
  green_blue_channel: 0,
  blue_red_channel: 0,
  blue_green_channel: 0,
  blue_blue_channel: 100,
  red_channel_offset: 0,
  green_channel_offset: 0,
  blue_channel_offset: 0,
  vibrance: 0,
};
