FROM python:3.14

WORKDIR /backend

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN apt-get update && apt-get install -y curl

COPY . .

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"]