services:
  db:
    image: postgres:18
    restart: unless-stopped
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    shm_size: 128mb
    networks:
      - wizpx_app

  pgadmin:
    image: dpage/pgadmin4:9.8
    env_file:
      - ./db/.env
    ports:
      - 5050:5050
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    image: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    networks:
      - wizpx_app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    image: backend
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3001/status" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wizpx_app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - images:/images
    networks:
      - wizpx_app

networks:
  wizpx_app:


volumes:
  frontend_node_modules:
  images:
