services:
  db:
    image: postgres:18
    restart: unless-stopped
    volumes:
      - ./db/postgres:/var/lib/postgresql
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    networks:
      - wizpx_app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    image: frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - ./frontend/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "http://frontend:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wizpx_app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    volumes:
      - ./backend:/app
    working_dir: /app
    ports:
      - 3001:3001
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "http://backend:3001" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - wizpx_app

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./backend/images:/images:ro
    depends_on:
      - backend
      - frontend
    networks:
      - wizpx_app

networks:
  wizpx_app: